### ISSUE TITLE
Read-only authentication / switching to new app and credentials?

### ISSUE THREAD

**Issue by dmgt** [r-box/boxr#100]
Thank you all for the continued development of this package. 

Is there a way to authenticate to `boxr` that allows read-only access? 

Previously I successfully used `boxr` per the instructions with the key and secret generated from API authentication through my personal organizational BOX account. 

Now I'm trying to switch the authentication credentials to use a different email and user account (also part of our organization) that has read-only access to our BOX folders, and followed the instructions to generate a new key and secret corresponding to this second email address. I deleted the old `.boxr-oauth` file, and put the new key and secret in the project `.Renviron`, and also tried `box_fresh_auth()`. Running `box_auth()` *does* read in the new values from .Renviron, but the pop-up Browser still asks if I want to authorize the new  app to have read and write access to my personal org BOX account (eg dana@org...) , whereas I was hoping to set it up to have access to read_only_account@org

Any suggestions on how to successfully switch to new credentials, or a better way to configure read-only access would be much appreciated.

**Comment by nathancday** [comment]
About switching users:
Copy the URL from the pop-up browser window and paste it into a new no-cookies browser window, like Chrome's Incognito. I find the browser recognition from Box.com redirects me automatically and this is the only way to get to the proper (secondary) authentication page.

About editing .Renviron for credentials:
Instead pass your `client_id` and `client_secret` to `box_auth()` in an interactive session, and let it handle refreshing and editing the hidden files for you.

About read-only access:
Not sure but seems like a Box account level thing.

**Comment by dmgt** [comment]
Thanks! This resolved the issue - by running `box_auth()` with `client_id` and `client_secret()` as explicit arguments, and copying the url that popped up into an Incognito/Private browser tab where I was already logged in to the BOX account with read only access, I was able to authenticate with the new account. 

For anyone else wondering about read-only access -  can confirm that once I'd authenticated with an account that had been previously set up to have read-only access to a particular BOX directory, it indeed still worked to use `box_read()` but `box_write()` gave HTTP error 403 forbidden. 

I also set the read-only access as an option in the app "Configuration settings" 

![image](https://user-images.githubusercontent.com/4704963/55356191-11ef8380-547f-11e9-929e-4ebf2bb84aa7.png)

**Comment by dmgt** [comment]
I was also able to use the workaround of authenticating on my local machine to generate a ` .boxr-oauth` file, and then copying that file to Rstudio running on a remote cluster to authenticate with the new account there as well. 

Here are the steps I used, after authenticating locally: 
1. Find the .boxr-oauth file (probably under Yourname/Documents, it's a global setting, not specific to an RStudio project)
2. In RStudio on your remote server, go to your root directory, click the "Upload file" button, upload this file from your file explorer and if prompted say yes to overwrite the previous file.
3. It probably won't show up in the file pane as a hidden file but re-running `box_auth()` can work
