### ISSUE TITLE
box_auth() fail to run

### ISSUE THREAD

**Issue by jf-dmp** [r-box/boxr#103]
Thanks for developing this package for R user! 

I recently tried to combine multiple data sets from box and pull it into R studio. I have set up the box developer environment (token + OAuth 2.0 Credentials) and it worked at the beginning. However, I was trying to do similar tasks couple days later and run **box_auth()** in my R studio console. And the error below kept popping up which make it fail to connect to box. Below is the detailed error message I received when I ran box_auth() in R:

> box_auth()
Reading client id from .Renviron
Reading client secret from .Renviron
createTcpServer: address already in use
Error in .subset2(public_bind_env, "initialize")(...) : 
  Failed to create server

Thanks for help!

**Comment by nathancday** [comment]
Looks like the underlying `httr` process might be hung. Can you run: `sudo lsof -i :1410` (in a terminal). Does it return anything? If it returns a process ID then run: `kill $process-id` and try `box_auth()` again.

**Comment by jf-dmp** [comment]
Hey Nathan:

    It asked me for the password. Do you know what password it asked for?

Thanks

**Comment by nathancday** [comment]
Yes, it wants the `sudo` password for the user account you are using on your local machine. It should be the password you use to login to your computer.

**Comment by jf-dmp** [comment]
Thanks Nathan! When I run "kill $process-id", should I refer the id to the PID?

**Comment by nathancday** [comment]
Yep, something like `kill 1073441`

**Comment by jf-dmp** [comment]
Thanks for your great help, Nathan! It works!

**Comment by nathancday** [comment]
Most welcome, glad it's fixed. Happy to help and if you end up loving `boxr` please consider 🌟ing it.

**Comment by jf-dmp** [comment]
Sure Absolutely! The package been very useful on my end!
