### ISSUE TITLE
R scheduler boxr can not be loaded 

### ISSUE THREAD

**Issue by jf-dmp** [r-box/boxr#104]
Hi forum:

   I am encountering an weird issue when I scheduling an R script to run on a hourly or daily routine. The script involves the step that load the **boxr** package. Everything run fine if I just run the whole script manually. However, when the scheduling process run, it keep throwing an error message saying that "**Error in library(boxr) : there is no package called 'boxr**'". Has anyone face this issue before? 

I truly appreciate your help!

Thanks

**Comment by nathancday** [comment]
I would guess that `boxr` is installed for your user account, but not for the system's root account. Can you check that you can attach `library(boxr)` when you are root?

**Comment by jf-dmp** [comment]
Hey Nathan:

   I have figured it out. I used the github comment to install the boxr package on the past. But I just used install.packages() commend and reinstall the package. Everything works now!

Thanks,
Joe

**Comment by nathancday** [comment]
Great!
