### ISSUE TITLE
Problems with box_dir_create()

### ISSUE THREAD

**Issue by RegenexxPRC** [r-box/boxr#106]
Hi all,

I've been having difficulty getting boxr to successfully create a file within my box directory. My code reads:

```
library(boxr)
box_auth()

my_file_dir <- box_setwd("76009318507")

box_dir_create(dir_name="TEST", parent_dir_id = my_file_dir)
```

after running which, I get the following output:

```
box.com remote folder reference

 name        : 
 dir id      : 
 size        :  
 modified at :  
 created at  :  
 uploaded by : 
 owned by    : 
 shared link : None 

 parent folder name :  
 parent folder id   : 
```

I've tried using additional arguments within box_dir_create, but according to the documentation only dir_name and parent_dir_name are accepted.

Any help is much appreciated.

**Comment by ijlyttle** [comment]
My understanding is that `box_setwd()` sets a default directory but returns nothing. 

What if you were to try:

```r
box_dir_create(dir_name="TEST", parent_dir_id = "76009318507")
```

**Comment by RegenexxPRC** [comment]
Hi ijlyttle,

That did it, thanks. I appreciate the prompt reply!

**Comment by RegenexxPRC** [comment]
@ijlyttle Do you know of an easy way to reference a newly-created box directory from R?

I'd like to upload a series of images based on date created, which is a variable in my script. So I have:

```
library(boxr)
box_auth()


box_UCR_Output <- "76009318507"

box_dir_create(dir_name=date_of_extract, parent_dir_id = "76009318507")

*** Code to create images ***

box_ul(file = location_of_image_files))

```

This uploads the images to the top of my directory (`box_UCR_Output`), but I would like them placed in the new directory `date_of_extract`. Is there a way to extract the dir_id from that new directory without having to pull it from the URL by hand?

Thanks for your help.

**Comment by nathancday** [comment]
`box_dir_create()` is quietly passing back a lot of useful information, including the newly created directory's ID, to access it just save the function results as a variable.

```
b <- box_dir_create("test_dir")

names(b) # lots of info

b$id # what you want

box_ul(b$id, "image_file.jpg") # is this file by file?
box_push(b$id, "image_directory/") # or a directory wide operation?
```
