### ISSUE TITLE
Should this line drop the !/negation

### ISSUE THREAD

**Issue by nathancday** [r-box/boxr#117]
https://github.com/r-box/boxr/blob/f85668d247895ccc6ff7c1afee7f4376c3125e06/R/boxr_write.R#L41-L43

@ijlyttle Re-reading this today to copy your pattern for deprecation in another package. Should the line linked above be `missing(file_name)` instead? I know I "reviewed" this already, so apologies for extra noise

**Comment by ijlyttle** [comment]
Hey @nathancday - 

I will look at it more-carefully later, but I think that it should be

```r
if (!missing(filename))
```

TRUE implies that someone has specified a `filename`, which is deprecated. I think I had neglected to change this when switching the argument to-be-deprecated from `file_name` to `file_name`.

**Comment by nathancday** [comment]
Hmm, I thought it should be `missing(file_name)` because then it would use the value `filename` and continue on.

**Comment by ijlyttle** [comment]
You're right, I wasn't looking at the full context:

https://github.com/r-box/boxr/blob/f85668d247895ccc6ff7c1afee7f4376c3125e06/R/boxr_write.R#L34-L44

What I was thinking about is caught in line 34; we should be setting `file_name` only if it is missing...
