### ISSUE TITLE
Stale auth

### ISSUE THREAD

**Issue by mauritzvdworm** [r-box/boxr#120]
I am working on a project with a team where they are adding data to a database and syncing with box.  I then download the data onto a cloud device and run batch files on the data.  It often happens that the auth is stale and I have to go to the specified URL to grant box access.  I have updated boxr and ran box_fresh_auth, but still betting these stale auth keys.  Any idea how to fix this?

**Comment by nathancday** [comment]
Two questions and one suggestion...

1) Are you using the current development version ( from Github)?

2) Do you call box_auth() from within your batch scripts?

- There is a PR open to support an alternate authentication method (JWT),
that is meant to make server/cloud usage easier. It's getting close to
being merged, but you might want to install that branch and see if it
solves your issue. See the vignette for Getting started and ?box_auth_jwt()
for more details.

**Comment by mauritzvdworm** [comment]
Hi @nathancday 

Thanks for the speedy reply!

> 1) Are you using the current development version ( from Github)?
Nope, CRAN version

> 2) Do you call box_auth() from within your batch scripts?
Yes.  I am thinking this could be the culprit.

> See the vignette for Getting started and ?box_auth_jwt() for more details.
I'll have a look

**Comment by nathancday** [comment]
Keep me posted. At the minimum I would use the Github version, `remotes::install_github("r-box/boxr")`, since the CRAN version hasn't been updated in years 😢 but we are targeting a CRAN release shortly 🍾

**Comment by mauritzvdworm** [comment]
Hi @nathancday 

The Github version works way better.  Haven't received a stale token in a couple days.
