### ISSUE TITLE
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

### ISSUE THREAD

**Issue by jtraurig** [r-box/boxr#121]
Receiving this warning in subject whenever I authenticate using boxr::box_auth(). Any idea why this is happening.

Reading client id from .Renviron
Reading client secret from .Renviron
Auto-refreshing stale OAuth token.
boxr: Authenticated at box.com as Jeremy Traurig (jtraurig@resurety.com)
Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

**Comment by nathancday** [comment]
I'm not sure right away, doesn't look like `box_auth()` ever calls `is.na()` directly...

Couple of clarifying questions:

1) Are you using the version from Github or CRAN? Try the Github version if you can

2) Are you using `box_auth_on_attach()`?

3) Does this happen in a clean R session?

**Comment by jtraurig** [comment]
1. From CRAN
2. Nope
3. Yes

I tracked it down to this call in box_auth() -- box_token <- httr::oauth2.0_token(box_endpoint, box_app, 
        use_oob = getOption("httr_oob_default"), cache = cache, 
        ...)

**Comment by nathancday** [comment]
Thanks for the info. I'll to figure out what is misbehaving in that token call

Can you use the Github version? The CRAN version is two years old at this point

It might also be worth checking if a httr update is available, I don't get the warnings with httr_1.4.1

**Comment by jtraurig** [comment]
FYI...session_info outputs the following so I've updated using the above and continue to receive the warning. All this said, I am still able to authenticate. Though it's unclear if this warning will become an issue down the road.

 boxr          0.3.4.99999 2019-09-09 [1] Github (r-box/boxr@ef46189)          
 httr          1.4.1       2019-08-05 [1] CRAN (R 3.4.4)
