### ISSUE TITLE
How to retrieve more than 200 csv file using box_search()?

### ISSUE THREAD

**Issue by jf-dmp** [r-box/boxr#122]
Hi, 

I am using the box_search function within the BoxR package to retrieve files from box. However, it looks like the function can only bring in max 200 files. Is there a way to extract the files that being missed?

Thanks!

**Comment by nathancday** [comment]
Hi @jf-dmp thanks for raising this issue.

The short answer is no. 

It actually looks like the `box_search()` function doesn't include new search results if you change the `max` argument. It does returns more results, but they are just duplicates:

```
x <- box_search("csv") %>% as.data.frame()
y <- box_search("csv", max = 550) %>% as.data.frame()
x  %>% dim() # 200
y  %>% dim() # 600
x %>% unique() %>% dim() # 200
y %>% unique() %>% dim() # 200
```

It might be possible to use `box_ls()` (which will return more than 200 unique files) instead if you can narrow your search down to specific folders. I often use a pattern like this:

```
box_ls(123000000) %>%
  as.data.frame() %>%
  dplyr::filter(grepl("search term", name)
```

I'm going to leave this issue open as I look into the unexpected behavior of `box_search()`.

**Comment by jf-dmp** [comment]
Hi @nathancday :

I just tried the box_ls() and it worked! Thank you so much for the help and is is an great option for my work!

Best,
Joe
