### ISSUE TITLE
box_search() returns duplicate results if max > 200

### ISSUE THREAD

**Issue by nathancday** [r-box/boxr#124]
Not sure why this is happening but discovered as I was investigating #122. Assuming we have more than 200 CSV files in an account:

```
x <- box_search("csv") %>% as.data.frame()
y <- box_search("csv", max = 550) %>% as.data.frame()
x  %>% dim() # 200
y  %>% dim() # 600
x %>% unique() %>% dim() # 200
y %>% unique() %>% dim() # 200
```

Two things a troublesome with this:

1. the duplication, I would expect 550 unique search results to come back in `y`
2. the rounding up to nearest 200, this could be an artifact of the pagination in the API or in boxr, but it might be worth digging into after 1

**Comment by ijlyttle** [comment]
My first guess is it's the pagination.
