### ISSUE TITLE
client ID & secret not saved

### ISSUE THREAD

**Issue by kdsilva** [r-box/boxr#147]
Hi,

I am not sure if this is an issue with my R environment or boxr. After setting the client ID/secret and verifying it is in the environment (Sys.getenv() ), everything works fine. If I restart R, the values are no longer there and box_auth prompts for them again. What might be the issue? Why are the values not being permanently saved?

Thanks!
KD

**Comment by nathancday** [comment]
For every new R session those values are re-loaded from a `.Renviron` file, which is *usually* located in your home directory `~/.Renviron`. You will need to edit the `.Renviron` file and add those as new key-value pairs, if you want them to always be available:

```
BOX_CLIENT_ID=your_client_id
BOX_CLIENT_SECRET=your_client_secret
```
Make sure the file ends in a new line, save the edits and restart your R session. Then you (and the boxr functions) should be able to access the variables, you can confirm with `Sys.getenv("BOX_CLIENT_ID")`.

See this [article](https://r-box.github.io/boxr/articles/boxr-app-interactive.html#use) for more details.

**Comment by kdsilva** [comment]
Thanks!  usethis::edit_r_environ() was helpful to locate the correct .Renviron file. I had found one on my harddrive that didn't match the variables shown with Sys.getenv() . I still can't find the file on my hard drive, but at least I can access it this way!

**Comment by nathancday** [comment]
Great! I'm glad you can get the proper variables configured. Does that get your problem resolved?

[This resouce](https://csgillespie.github.io/efficientR/3-3-r-startup.html#rprofile) might be useful if you ever need to track down where the `.Renviron` is on your system. I actually copy mine over when I switch computers b/c its a pain to set up.
