### ISSUE TITLE
Remedy Travis config warnings

### ISSUE THREAD

**Issue by nathancday** [r-box/boxr#150]
Deprecation warnings for build arguments that need to be addressed.

<img width="621" alt="Screen Shot 2020-04-25 at 10 56 42 AM" src="https://user-images.githubusercontent.com/808225/80283164-af999e80-86e3-11ea-9a5c-9d3154f266a3.png">

**Comment by ijlyttle** [comment]
I wonder if this is a sign that we should consider GitHub Actions?

**Comment by nathancday** [comment]
Yea it mightbe. I remember being excited about GH actions at rstudio:conf, but I can't remember why exactly.

It seems like they offer the same features, and importantly the support for [encrypted ENV vars ](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets). So maybe we make that a goal for 3.6?

**Comment by ijlyttle** [comment]
Sounds good!
