### ISSUE TITLE
Extend support around Box collaborations

### ISSUE THREAD

**Issue by nathancday** [r-box/boxr#151]
The use of "Service" accounts means using `box_invite()` to create write permissions for specific files/folders, the Box API refers to these as [Collaborations](https://developer.box.com/reference/get-collaborations-id/). `box_invite()` works great for creating a new collaboration, but errors if your try to create an existing collaboration.

Instead of just adding a check internally to `box_invite()` I propose we expand the support for Collaborations in general because of their elevate importance in the "Service" account model.  Something similar these functions seem like enough to manage existing collaborations:

* `box_dir_collaborators(dir_id = 0)` - see all existing collabs on sub-directories
* `box_file_collaborators(file_id)` - see all existing collabs on file
* `box_delete_collaboration(collab_id)` - remove an existing permission

I'm sure there are another use cases I haven't considered, but want to put this idea on the wall. I see this is getting close to writing that `cardboard` API level package, I just can't envision where a clean break line would be between that and `boxr`.

**Comment by ijlyttle** [comment]
This is just a first thought, but how about:

- `box_create_collab()` returns a collaboration object
- `box_get_collab()` returns a list of collaboration objects

For these two, the user could provide **one** of a `file_id` or a `dir_id`. We might have to build some structure around a collaboration object to make it user-friendly.

This would deprecate `box_dir_invite()`. Also, I like the verb `invite`, but I also like the consistency of using `create`...

- `box_delete_collab(collab_id)`

**Comment by nathancday** [comment]
I like the naming changes.

I'm not sure how much we can/should homogenize files and folders, because of the [API split between the two](https://developer.box.com/reference/get-files-id-collaborations/) and because of the pattern established in other boxr functions. I think it would work fine for working with the Collaboration IDs, but my feeling is most people would want to operate on the file/folder IDs.

**Comment by ijlyttle** [comment]
Yeah - I see where you are coming from - I think you are right, but I started seeing the names get longer... maybe it just has to be that way:

```r
box_create_collab_dir()
box_create_collab_file()
box_get_collab_dir()
box_get_collab_file()
```

?

**Comment by nathancday** [comment]
I think the long names might be unavoidable, but at least those would be descriptive and close to Box API actions

**Comment by ijlyttle** [comment]
continuing the [discussion](https://github.com/r-box/boxr/issues/97#issuecomment-665233250)

how about:

```r
box_collab_create(file_id = NULL, dir_id = NULL, ...)
box_collab_delete(collab_id)
box_collab_get(file_id = NULL, dir_id = NULL, ...)
```

But should it be `box_collab_get()` for consistency, or `box_collabs_get()` for descriptiveness?

**Comment by nathancday** [comment]
I think that is the best option yet, and I prefer the consistency of `collab` (singular) too. I'll make those adjustments...

**Comment by ijlyttle** [comment]
Thanks! API tennis is one of my favorite things!

**Comment by nathancday** [comment]
closing with #155
