### ISSUE TITLE
box_push changes foler name to location identifier

### ISSUE THREAD

**Issue by mauritzvdworm** [r-box/boxr#153]
I have a local folder that gets updated daily with nested folders and contents within each.  Normally I make use of box_push to push all the contents to the cloud.  Today I noticed that one of the sub folders was renamed on the cloud to an alphanumeric name that looks the the box_id.  It does not happen when I upload the particular folder manually from a web browser.  Any ideas what is happening here?

**Comment by nathancday** [comment]
Box ids are always integers, so alphanumeric is bizarre. Since it's only one folder, it seems weird that `box_push` would be doing it sporadically. Can you share an example of the code to reproduce the issue? One guess in the dark is a character encoding issue.

**Comment by mauritzvdworm** [comment]
Hi @nathancday,

I use the same code in many other place without any issue.  What I normally do is to specify the path to the folder I want to push.  In the dir_id I enter the folder ID where I want the contents to be placed.  Next step is to push.

`
path <- "C:/.../.../my_path"
box_push(dir_id="...", local_dir = path, overwrite = TRUE)
`

The specific folder name that gets messed up is _C vs SB_.  The other folders have names like _C vs S_, _C vs KW_, ..., _SB vs QW_ and push without any problem.

Any ideas?

**Comment by nathancday** [comment]
So the local file is named `C vs SB/`? Can you do a `list.dir("path/to/parent_folder_of_CvsSB)` so I can see all of the file names as they get printed to the console

I think if the code is working fine other places chances are good it is something peculiar to the problem folder.

**Comment by nathancday** [comment]
Can you also share the folder name and the folder ID of what it becomes on Box?

**Comment by mauritzvdworm** [comment]
Sure, the folder should be _C vs SB_ but takes the nane

`
113933477865B
`
When I enter this folder the folder id is 

`114045723048`

I attach a screenshot

![screenshot](https://user-images.githubusercontent.com/12235418/82914538-f04d3780-9f6f-11ea-834b-d8173a4ba5a4.png)

**Comment by nathancday** [comment]
Can you try just pushing the problematic folder by itself? I wonder if the name (C vs SB) gets coerced to the same value (113933477865B) everytime...

**Comment by mauritzvdworm** [comment]
I created a temp folder and put the C vs SB folder inside.  Next I updated the path to

`path <- "C:/.../.../my_path/temp"
`
and pushed the contents to box with
`
box_push(dir_id="...", local_dir = path, overwrite = TRUE)
`

This created the C vs SB folder.

**Comment by mauritzvdworm** [comment]
Seems to work correctly now.  Thanks for the help!

**Comment by nathancday** [comment]
Glad you found a way around it.
