### ISSUE TITLE
Expand `box_search()` documentation explaining how to do an exact search

### ISSUE THREAD

**Issue by ashirwad** [r-box/boxr#154]
I was struggling to search an exact file using the `box_search_files()`  function because putting the exact filename in the `query` argument still returned a ton of extra files that I didn't need! Then I came across [this discussion](https://community.box.com/t5/Platform-and-Development-Forum/Is-there-a-way-to-do-an-quot-exact-quot-search/td-p/21099) that indicated that to do an exact search we need to supply the following value to the `query` argument: `"\"exact filename\""` I think it will be helpful to future users if you added this information in the description for the `box_search()` function!

**Comment by nathancday** [comment]
Thanks for flagging this improvement and glad you are enjoying boxr.

So right now the docs say:

```
* Phrases can be searched
  - by putting them in "quotation marks".
```

What edits do you suggest to make it clearer?

**Comment by ashirwad** [comment]
I would say the following:

```
* Phrases can be searched
  - for a fuzzy match by enclosing the search term within quotation marks (e.g., "search term"), or
  - for an exact match by escaping the quotes with backslashes (e.g., "\"search term\"")
```

How does it sound?

**Comment by nathancday** [comment]
I like the idea of showing the examples, I think that's the essential bit to help future users. I'm a little worried bout the fuzzy match bit causing confusion.

What do you think about:

```
* Phrases can be searched
  - by surrounding them with "quotation marks"  in the query string e.g.`box_search("'match this phrase exactly'")`
```

**Comment by ashirwad** [comment]
I will suggest a minor change:

```
* Phrases can be searched
  - by surrounding them with "quotation marks" in the query string e.g. `box_search("match similar phrases"), `box_search("'match this phrase exactly'")`
```

I added another example to make it clearer that even though we search "myfile.csv", we may end up with many other similar looking files. But you may choose to ignore it if you think it's not adding much value!

**Comment by nathancday** [comment]
I like your idea to highlight the different behaviors side by side and I just realized we don't actually have any examples on the `?box_search()` help page! I think that would be the best place for these snippets. 

Are you interested in making a PR to add those two use cases to the docs? 100% happy to pair on it if you've never worked with docs / `roxygen2`

**Comment by ashirwad** [comment]
I can't find the file that I need to edit. Can you please point me to that?

**Comment by nathancday** [comment]
`R/box_search.R`

**Comment by ashirwad** [comment]
Thanks, @nathancday! I submitted a pull request. Also, `box_search("'match this phrase exactly'")` doesn't perform an exact match.  We need to skip the quotation marks with backslashes like I showed before:  `box_search("\"match this phrase exactly\"")`
