### ISSUE TITLE
Auto run an R script when a new version of a Box file is available

### ISSUE THREAD

**Issue by ashirwad** [r-box/boxr#161]
Hey @nathancday, I was wondering if it's possible to run an R script when a newer version of a file is available on Box?

Here's my use case: My project manager pushes some data on Box, I have an R script that computes different metrics, and finally I push the file back on Box. I want to automate this process so that every time she makes a change upstream, I want to run the R script.

In a knitr chunk, I can add the option `cache.extra = box_current_version(file_id)` to recompute things when a newer version of a Box file is available. But I am not sure how I can actually do that for an R script! Do you have any suggestions? 

Thanks!

**Comment by nathancday** [comment]
@ashirwad I'm glad you find boxr useful, please consider starring the package to show your support.

Sounds like you a building a custom workflow around Box, which is awesome. Obviously I have no idea about the details of your project, but this sounds like you will need to run scheduled job to do the checking. I've used [cron](https://en.wikipedia.org/wiki/Cron) before for similar things, not specifically boxr.

**Comment by ashirwad** [comment]
Thanks for the pointer, @nathancday! I will take a look at the package.
