### ISSUE TITLE
box_add_description() should be box_file_update()

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#169]
The Box API offers a lot of things with their [file-update endpoint](https://developer.box.com/reference/put-files-id) - I think this function could be expanded and renamed.

To be clear, I am not suggesting we do this on *this* (Aug. 2020) release, but perhaps soon thereafter.

**Comment by ijlyttle** [comment]
We have a lot of open issues that seem to hit the same API endpoint: [File Update](https://developer.box.com/reference/put-files-id/):

- this one, concerning the description
- #182 to lock files
- #167 to copy files

We already have an internal function `box_file_update()` - used by `box_ul()` 

We also have an incidental issue, #174 on file metadata, potentially related, as it concerns the Box API file object.

Not considering immediate action other than to close #182 and #167, combining them into this issue.

**Comment by nathancday** [comment]
I've personally never used the `boxr_add_description()` once I found out it wasn't a comment, non-API users could see. It does feel like we are missing some functionality and agree about expanding to support the lock/copy/link/move behaviors.

**Comment by ijlyttle** [comment]
closing in favor of #208
