### ISSUE TITLE
documentation tweaks

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#170]
As a "final" step before starting the release process, I want to dedicate a PR to documentation, particularly harmonizing things - either for new functions, or for new thinking.

- [x] check that we are taking care of parameter inheritance
- [x] consistency of `version_id` and `version_no`
- [x] update README to highlight new features (Ian)
- [x] update `vignette("boxr")` as needed (Ian)
- [x] add documentation on uploading to RStudio server/cloud (#180) (Nate)
- [ ] describe more explicitly the compromise on returning API responses vs. data frames (begin a `vignette("design")`). (Ian)
- [x] add some words about JWT time-offset in service-apps vignette. (Ian)
- [x] add new functions to pkgdown function-reference (Nate)
- [x] note which functions are superseded and which are deprecated (Nate)
  - [x] add tidyverse tag for superseded/deprecated?
  - [x] make sure we use the newer functions in function docs and articles
  - [x] add **Superseded** section to function reference (`collab()` deprecates `dir_invite()`, `history()` supersedes `prev_versions()`)
  - [x] update **Deprecated** section of function reference (remains deprecated `box_auth_on_attach()`, still in package)
- [x] ensure consistent function-titles and -return values

**Comment by ijlyttle** [comment]
That sounds great! Let's get the code changes done, then set up a Zoom call.

**Comment by ijlyttle** [comment]
Edited list to include:

- documentation on uploading credentials to RStudio Server/Cloud
- make more explicit the compromise of returning API responses instead of data frames.

**Comment by nathancday** [comment]
Just pushed up several commits, make sure to pull if you are editing anything.
