### ISSUE TITLE
Clearer guidance on uploading auth to RStudio Server et al.

### ISSUE THREAD

**Issue by malcolmbarrett** [r-box/boxr#180]
Thanks again for this great package. The documentation being so clear has been very helpful for us.

One issue members of our team have bumped into is actually finding the auth file to upload to RStudio Server. For instance, on a Mac, you need to add your home directory to Finder, then use the keyboard shortcut `cmd + shift + .` to see it. Since it's a little unclear even to advanced users, I thought the articles could include clearer guidance in this respect. It's dangerously close to out-of-scope, but at least on a Mac, it's not too rough to explain (I don't know if or what issues there are on Windows and Linux). 

What do you think? Happy to work on a PR if you think it would be useful here.

**Comment by nathancday** [comment]
Never opposed to making the docs more clear. What do you think about adding a helper function to open that file in a file browser window? I'm thinking we wrap some `fs` (which we already import) path creator with `open()` and get a platform agnostic solve.

**Comment by ijlyttle** [comment]
If I am thinking about this correctly, we are following [this scenario](https://support.rstudio.com/hc/en-us/articles/200713893-Uploading-and-Downloading-Files), where a Mac user is running RStudio Server remotely through their web browser.

Would we need to intercept the call to the "Upload" button? Is there something in the [rstudioapi package](https://rstudio.github.io/rstudioapi/index.html) that could be helpful?

**Comment by nathancday** [comment]
I was thinking `system("open ~/.boxr-auth/")` on the local machine.

**Comment by malcolmbarrett** [comment]
Hm! A helper function may be helpful. Can you drag and drop a file to the upload menu on RStudio Server? That would be a nice general solution. The issue we've bumped into is configuring the upload window to show the directory and hidden file (as you don't get access to some of the other tools like "Go" in Finder)

**Comment by nathancday** [comment]
I don't think the helper will get around the default behavior in Finder, looks like you'd still need Cmd+Shift+period if we keep using the `httr` default of making the token text file hidden. Feels like a doc edit to reference the Mac Finder instructions is the play, unless we want to buck the hidden file default.

You can drag and drop into Cloud, if you release near the File Upload section.

**Comment by malcolmbarrett** [comment]
Oh yeah, I didn't expect it too and think it's reasonable to use the httr standard. I think a helper function to open + a little guidance in the docs on viewing hidden files will be enough to get users there!
