### ISSUE TITLE
Lock Files

### ISSUE THREAD

**Issue by alexbrodersen** [r-box/boxr#182]
Is connection to the file lock API being planned?

It's available via the update file feature:
https://developer.box.com/reference/put-files-id/

**Comment by alexbrodersen** [comment]
I would be happy to put in a PR for this, if desired. After doing some local testing, it would be much easier using functions from the jsonlite package, which is currently listed as suggests in the DESCRIPTION file.

Since httr imports jsonlite and boxr imports httr, I think it is fair to import jsonlight as well, correct?

**Comment by ijlyttle** [comment]
Thanks! 

There we seem to have a few issues that concern the file-update API endpoint. I suspect we will try to take all of them on at once.

**Comment by ijlyttle** [comment]
By the way, @alexbrodersen nice catch to note that {jsonlite} is suggested, rather than imported! We are *definitely* using it as an import.

I am changing {jsonlite} in the DESCRIPTION file to deal with another issue.

**Comment by ijlyttle** [comment]
closing in favor of #208
