### ISSUE TITLE
Request failed [400]

### ISSUE THREAD

**Issue by jtraurig** [r-box/boxr#192]
When I authenticate via box_service_auth() i consistently get Request failed [400] errors. It retries and eventually authenticates but occasionally it just fails. Why are these failures happening and is there something that can be done about it?

![image](https://user-images.githubusercontent.com/55104463/95346303-b24f1100-0889-11eb-8d64-930d6df33e36.png)

**Comment by ijlyttle** [comment]
We are looking at this issue in #166.
