### ISSUE TITLE
Mapping Directory Path or File Path to Box Id

### ISSUE THREAD

**Issue by jtraurig** [r-box/boxr#196]
Hello all,

Apologies but this isn't an issue. I'm new to boxr but this there a way that one can pass the full directory path from box.com and convert that to a boxId in a simple command? I just want a simple way to map directory names / paths to box ids such that I can then quickly perform other operations on those paths / files.

**Comment by nathancday** [comment]
Can you give an example of "full directory path from box.com"?

Box URLs represent folders by ID, which can be used with `box_ls()`

**Comment by jtraurig** [comment]
Hi Nate,

Yeah. Sorry that isn't clear. What I mean is if a user gives me a path in
box like this *dirName1/dirName2/dirName3,* is there an easy way to get the
box id of dirName3. Yes, I can use box_ls() but that requires me to get the
boxId of dirName1 then dirName2, just to get to dirName3, so essentially I
have to write a loop that gets me the ids of each of the prior box
directories before I get to to the id of the directory I want to work in.
Writing a loop to do this isn't a big deal but I was wondering if there was
an easier way that I'm missing.

Thanks -- Jeremy

*Jeremy Traurig*
VP, Engineering - Transaction Services
REsurety, Inc
(617) 631-8612

**Comment by ijlyttle** [comment]
I have not used it myself, but could `box_search_folders()` be useful here? https://r-box.github.io/boxr/reference/box_search.html

**Comment by nathancday** [comment]
Linking #157

**Comment by jtraurig** [comment]
Thanks for all the help here. My plan is to just build a function that will map the ideas if a user provides a path.
