### ISSUE TITLE
shinyapps.io

### ISSUE THREAD

**Issue by fmmattioni** [r-box/boxr#213]
Hi all!

I have noticed that since a few commits (I am not sure exactly which one) there is an issue connecting to the box API when deployed in shinyapps.io.

Checking the logs, I get the following:

`Warning: Error in test_request: Bad Request (HTTP 400). Failed to connect to box.com API.`

I have been using this commit without problems: `b9b733b7bf2f80cb8a4854babdf200955321cbf0`.

Let me know if I can help with anything.

**Comment by fmmattioni** [comment]
FYI: everything works locally, though.

**Comment by nathancday** [comment]
I noticed something similar last weekend, but haven't done a proper reprex
yet. Does `box_auth_service()` work locally for you?

**Comment by fmmattioni** [comment]
It does - both with the latest version and the one I am using in shinyapps.io (`b9b733b7bf2f80cb8a4854babdf200955321cbf0`).

**Comment by fmmattioni** [comment]
Hey guys, any news on this? I have been getting now the same error `Warning: Error in test_request: Bad Request (HTTP 400). Failed to connect to box.com API.` with the `b9b733b7bf2f80cb8a4854babdf200955321cbf0` sometimes.

**Comment by nathancday** [comment]
Remote machines (especially containers like ShinyApps relies on) make debugging very hard. And the package code seems to be working as expected. I don't believe this something we can fix at the boxr level. If you figure something out feel free to re-open this with additional details.
