### ISSUE TITLE
Unable to access public document

### ISSUE THREAD

**Issue by bzigterman** [r-box/boxr#214]
I'm not sure if this is a feature request or user error, but I can't figure out how to access this document: https://uofi.app.box.com/s/nrrnx2fn6sqt4hhuh2ckq2u6z5o4zmqg/file/781566755894

I'd like to be able to read this CSV directly, but it doesn't seem possible.

I've tried`box_dl(file_id = "780293011768")` and `box_read_csv(file_id = "780293011768")`,
but get back a 404 error `Error downloading file id 780293011768: Client error: (404) Not Found`.

Is it possible to get this document? 

Thanks for any help!

**Comment by ijlyttle** [comment]
Does this work?

```r
box_dl(file_id = "781566755894")
```

**Comment by bzigterman** [comment]
Nope. Same error: `Error downloading file id 781566755894: Client error: (404) Not Found`

**Comment by ijlyttle** [comment]
Have you run `box_auth()`?

**Comment by nathancday** [comment]
Maybe the ID is incorrect or the authenticated account does not have
permissions.

**Comment by bzigterman** [comment]
I ran `box auth()` and got 
```
Using `BOX_CLIENT_ID` from environment
Using `BOX_CLIENT_SECRET` from environment
boxr: Authenticated using OAuth2…
```
and ran into the same 404 error when trying to download the file.

I agree, it does seem like an authorization issue.

**Comment by ijlyttle** [comment]
Forgive me asking a very basic question, but is the Box app (`BOX_CLIENT`, etc. ) associated with the University of Illinois' Box, rather than to a personal account on Box?

**Comment by bzigterman** [comment]
That's OK. I'm a bit of a novice. My Box app is associated with my personal Box account, which I think may be the problem, as the document I'm trying to access is on the University of Illinois Box.

**Comment by ijlyttle** [comment]
I think that's it - you'd need an account with the University of Illinois Box, and set up an app (or use an existing app) there.

**Comment by ijlyttle** [comment]
I think this issue is resolved, insofar as it is in this package's power to resolve it.
