### ISSUE TITLE
box_ul issue - Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by gabitante** [r-box/boxr#217]
When I've tried to upload a file to box, it gives this error: Error: $ operator is invalid for atomic vectors. I have checked my authorization and believe it has been done correctly, have tried changing the dir_id  to different folders, tried uploading different types of files, and all give this error, so I think I'm doing something very basic incorrectly. Any help is greatly appreciated, thanks for your time!

box_ul(dir_id = 0, "Desktop/TEST.xlsx")

**Comment by nathancday** [comment]
Hrmm, that's frustrating. Do you know what version of `boxr` you are running? Check with `sessionInfo("boxr")`.

That error message feels familiar, wondering if we've fixed it in the version here on Github...you might try installing the dev version with `remotes::install_github("r-box/boxr"`.

Let me know how that all shakes out.

**Comment by gabitante** [comment]
Thanks for this support! I checked and am running boxr_0.3.6.9000, which I believe is the latest version?

I tried installing the dev version and restarted RStudio, but the same error is coming up for some reason. I'll keep trying other fixes but am confused about what might be going on! Thanks again for your help!

**Comment by nathancday** [comment]
You are right about version numbers.

Can you get the full Traceback for the error and it here as a code block? Also is this a new file or an existing file you are tying to upload?

FWIW `box_ul` works as expected for me with the dev version in new/update scenarios. We'll figure it out

**Comment by gabitante** [comment]
I am trying to upload an existing file (I made an excel file with just a few entries as a test). Here is what traceback() gave me:

1: box_ul(dir_id = 131791297577, "Desktop/TEST.xlsx")

I'd wondered whether my computer is doing something weird with the pb default (which does have a $ in it) but guessing that is too simple a reason for this coming up!

**Comment by nathancday** [comment]
That trace doesn't tell us anything new. 

Have you successfully uploaded files before?

**Comment by gabitante** [comment]
Through other means yes, not through R. I've tried pdfs etc. but the issue comes up there as well. I also get this error when I try to use box_write, but I can successfully download files from the box folders I specify, so I don't think it's an authorization issue.

**Comment by nathancday** [comment]
Read and Write permissions can be different, that sounds like you don't have Write permissions to that Box directory from your R app.  And are you using an interactive or service app?

**Comment by gabitante** [comment]
Hmm I believe I have the appropriate permissions - I'm using the Box developers app creation, here are the permissions I'm using: 

<img width="925" alt="Screen Shot 2021-07-15 at 9 55 49 AM" src="https://user-images.githubusercontent.com/62772082/125800113-6c354c29-9504-475b-8ac6-bce0cda12b92.png">

**Comment by nathancday** [comment]
So you are using the service app?

**Comment by gabitante** [comment]
Gotcha, I believe that's right then - though I'm happy to switch to interactive if that is more appropriate for what I'm trying to do?

**Comment by gabitante** [comment]
I made sure the app itself is interactive and am still having the issue for some reason! I tried enabling additional options in the configuration but that didn't change anything.

**Comment by nathancday** [comment]
hmm, I dunno whats going on. Sorry your getting stuck on that cryptic error.

I'm running out of ideas here, want to try a video call debug, as a last resort?

**Comment by gabitante** [comment]
I'm sorry this has been so difficult - that would be great if you don't mind!

**Comment by nathancday** [comment]
How does Monday afternoon work for you, say any time between 1-4p EDT?

**Comment by ijlyttle** [comment]
Hey all, sorry to jump in late - I'm glad you're getting together to figure this out, I thought maybe I could leave some conversation starters.

The error comes from boxr trying to parse non-existent content returned from box.com. We saw something similar in #197 - in that case, the content is always empty; in this case we are expecting a file reference.

@gabitante: If forced to guess, I'd say that you are not authorized to the folder you are trying to access. One thing you might try is `box_ls(dir_id = "131791297577")` (or whatever your folder id is) and make sure you get the answer you expect.

Is it possible you have more than one Box account? This has happened to me, where boxr is using the interactive app for my personal Box, but I really want boxr to be using the interactive app for my work account.

Best of luck!

**Comment by gabitante** [comment]
Hi All,

Thank you both for your support - weirdly enough, I sent the code I used to my coworker and for them it’s working, and for the project we are good to go as long as it works for one of us! I will try the latest suggestions you gave, but don’t want to use more of your time as long as we have a working solution. I’ll post again if checking the potential issues you both outlined again brings a solution, I appreciate your time and help!

George
