### ISSUE TITLE
Question: How to use boxr that uses SAML/Okta authentication

### ISSUE THREAD

**Issue by tamuanand** [r-box/boxr#224]
I have a box account managed by my institution - authentication to box happens via SAML/Okta. 

I would like to use `boxr` from a jupyter notebook on a linux server and I want to access files/folder in the box account. 

How do I go about this? 

Thanks in advance.

**Comment by nathancday** [comment]
As I understand SAML/Okta for login is independent of your ability to create "Box Applications", which is what `boxr` uses to do  its magic. The permissions on who can create apps are controlled by your Box Administrator. You should check and see if you can create a new application as a first step. See this page for details on that:  https://r-box.github.io/boxr/articles/boxr-apps.html

**Comment by tamuanand** [comment]
Hi @nathancday 

To give some context, if the organization url is something like `https://my_organizatio.app.box.com/folder/0`, we have a bunch of files/folders there and I want to use `boxr` to do some API calls. I am unable to get past the `box_auth()` step.  Not sure where I am doing it wrong.

**Details below:**

I worked with my sysadmin and was able to get the `client_id` and `client_secret`.  I am trying this below from RStudio on a Windows 10 laptop. 

```
library(boxr)
box_auth(
  client_id = "my_client_id",
  client_secret = "my_client_secret"
)
```

When I try the above, it redirects me to a URL and gives an error
```
Error: redirect_uri_mismatch
response_type=code
redirect_uri=http://localhost:1410/
state=HgmGkWcEBO
client_id=my_client_id
```

This is my `sessionInfo()`

```
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] boxr_0.3.6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       fansi_0.5.0      later_1.3.0      utf8_1.2.2      
 [5] crayon_1.4.2     R6_2.5.1         lifecycle_1.0.1  magrittr_2.0.1  
 [9] pillar_1.6.4     httr_1.4.2       rlang_0.4.12     curl_4.3.2      
[13] promises_1.2.0.1 vctrs_0.3.8      ellipsis_0.3.2   tools_4.1.1     
[17] purrr_0.3.4      httpuv_1.6.3     compiler_4.1.1   askpass_1.1     
[21] pkgconfig_2.0.3  openssl_1.4.5    tibble_3.1.5
```

My sysadmin also provided me with a JWT and I tried it as below - only for it to give me an error.

```
box_auth_service(token_text = 'my_long_token_text_string')
Error: lexical error: invalid char in json text.
                                       my_long_token_text_string
                     (right here) ------^
```

**Comment by tamuanand** [comment]
Hi @nathancday 

I have made **_some headway_** on the above. I was able to work with my sysadmin to have a new Oauth2 app and I was able to authenticate with `client_id` and `client_secret` on RStudio from windows laptop

**Important**: [This page](https://r-box.github.io/boxr/articles/boxr-app-interactive.html) states `Set Redirect URI to http://localhost` in the section `Set OAuth2 Parameters`. Setting it this way did not work.  I had to set redirect URI to `http://localhost:1410' and only then I was able to authenticate successfully.

**Need help here**: My ultimate goal is to be able to use `boxr` from a Jupyter notebook on a linux server. I am unable to get this going and I would like some help. This is what I have done so far:

1. Followed instructions from https://r-box.github.io/boxr/articles/boxr-app-interactive.html pertaining to the section `Transferring token to RStudio Server`
2. Copied over the contents of `.Renviron (BOX_CLIENT_ID, BOX_CLIENT_SECRET)` from Windows to my linux server and kept it in my home dir. Also made sure `.Renviron` ends with a new line (wc -l = 3)
3. Copied over `.boxr-oauth` file from Windows to my linux server and kept it in my home dir
4. Ensured httr package is same version on my laptop and R environment in linux

When I do the above on the Linux server, I am unable to authenticate successfully after the browser popup.

Please let me know what I should do to get this working.

Thanks

**Comment by nathancday** [comment]
Glad you got something working. Have you tried to use a "service app" instead of an "interactive app"? That is the method I would recommend for a server situation like you have.

**Comment by tamuanand** [comment]
@nathancday I tried it - see https://github.com/r-box/boxr/issues/224#issuecomment-1017091157 in this very same issue

I get this weird error - googled it and tried out all the suggestions from SO. Any suggestions from your end?

```
box_auth_service(token_text = 'my_long_token_text_string')
Error: lexical error: invalid char in json text.
                                       my_long_token_text_string
                     (right here) ------^
```

**Comment by nathancday** [comment]
Ultimately the `token_text` argument is processed with `jsonlite::fromJSON(token_text)`. Can you try that directly, another option is to use the `token_file` argument instead, which essentially reads in the contents with this code:
```
glue::glue_collapse(
        readLines(token_file, warn = FALSE),
        sep = ""
      )
```
I'm wondering if new line character are causing your text to not be parse-able/invalid JSON.

**Comment by nathancday** [comment]
your token text will look something like this. Just showing that valid JSON will parse without error
```
jsonlite::fromJSON('{
  "boxAppSettings": {
    "clientID": "4jm8myh2x02vuc4j0y7jo21x11ondgqt",
    "clientSecret": "2R4kVcLXoZN0uLM1EqN5o166jawDssPB"}}')
```

**Comment by tamuanand** [comment]
Hi @nathancday 

I will work with my sysadmin to get the JWT file as json.  

A question: Should I use the file as such after renaming/placing it as `~/.boxr-auth/token.json` or should I remove the `appAuth section containing the lines which have publicKey, privateKey, passphrase`

**Comment by nathancday** [comment]
Keep `token.json` as is, you should not have to edit it.

**Comment by tamuanand** [comment]
Thanks @nathancday
