### ISSUE TITLE
[Question]: Is it possible to use boxr to upload to S3

### ISSUE THREAD

**Issue by tamuanand** [r-box/boxr#229]
Hi @nathancday 

I wanted to know if it is possible to use boxr to upload files from box to S3 

Thanks in advance

**Comment by nathancday** [comment]
You could use it to download the files from Box to your local machine. Beyond that you'd need to use another package/method to upload them from local to S3.

See this Box Community thread for other ideas: https://support.box.com/hc/en-us/community/posts/360049154094-Box-to-Aws-S3
