### ISSUE TITLE
What redirect URI to use?

### ISSUE THREAD

**Issue by swood-ecology** [r-box/boxr#230]
What redirect URI should be set when creating the Box app? I followed all of the steps and got the following error:

```
Error: redirect_uri_mismatch
 Show Error Details
response_type=code
redirect_uri=http://localhost:1410/
state=ELIisfSGj3
client_id=
```

What's weird is the redirect_uri given in the error message is not the uri specified in setting up the app

**Comment by swood-ecology** [comment]
Adding http://localhost:1410/ to my list of approved URIs did the trick! Thanks.

**Comment by nathancday** [comment]
should we update the docs to reflect the `:1410` port spec that's required?
https://r-box.github.io/boxr/articles/boxr-app-interactive.html#create

**Comment by IsabelFE** [comment]
I agree, the documentation should be updated.

Thanks!
