### ISSUE TITLE
Move jose from suggests to imports

### ISSUE THREAD

**Issue by botan** [r-box/boxr#235]
Here is the bug I just encountered. `boxr` requires the `jose` to work. However, in the description, `jose` sits under suggests instead of imports.
```
boxr::box_auth_service()
#> Error: Package(s): "jose" needed for this function to work. Please install.
```
That also causes an issue when using `renv`. Since `jose` is not a dependency of `boxr`, `renv` cannot find and install it as a dependency. I'm happy to make a PR to fix it if you give a green light.

**Comment by nathancday** [comment]
green light!
