### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    Couldn't connect to server

### ISSUE THREAD

**Issue by htmlsrinu** [r-box/boxr#63]
Receiving the following error's while trying to authorize the box_auth() with valid Client ID and Client Secret.

Tried executing within my corporate environment and even with private Home wifi connections too, for proxy settings. 

Any help would be appreciated !!!

Error message while trying to execute box_auth():

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server

**Comment by ijlyttle** [comment]
This sounds like it might be a proxy problem - this is how such a problem presents to me. Without more information on the context, it is impossible to provide more help. 

Closing for now. Despite my very slow response, I am happy to continue the discussion.
