### ISSUE TITLE
can we replace internal function skip_on_travis()?

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#88]
There is an internal function: `boxr:::skip_on_travis()` that looks a lot like `testthat::skip_on_travis()`.

**Comment by nathancday** [comment]
Seems like that is no brainer as `testthat` is already being suggested.

**Comment by brendan-r** [comment]
Apologies, this was (IIRC) a temporary work around when `skip_on_travis` was in the dev-build of `testthat`, but not yet on CRAN (~4 years ago). Assuming `testthat::skip_on_travis()` is still a thing, removing the boxr version should be free of consequence.

**Comment by ijlyttle** [comment]
I figured it was an at-the-time workaround; happy it has worked all this time, and that we can replace it now with the testthat function.
