### ISSUE TITLE
consider using tibble() vs. data.frame()

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#91]
followon from #80, we are already importing `dplyr` so we are not adding to the dependencies...

**Comment by nathancday** [comment]
For awareness this is being discussed as an open issue in rio right now too. https://github.com/leeper/rio/issues/197

**Comment by ijlyttle** [comment]
I can see a future where dplyr and tibble become suggested rather than imported. We could support both `tibble` and `data.frame`. 

To do this [easily](https://github.com/r-lib/roxygen2/commit/843432ddc05bc2dabc9b5b22c1ae7de507a00508#diff-8312ad0561ef661716b48d09478362f3), we would implicitly depend on R 3.6.
