### ISSUE TITLE
Add function to open browser and see files on box

### ISSUE THREAD

**Issue by nathancday** [r-box/boxr#98]
I have this little function in my work package and get a lot of mileage out of it. Would something a bit more robust (to handle files and folders) be on brand for boxr?

```
function (box_dir) 
{
    url <- paste0("https://hemoshear.app.box.com/folder/", box_dir)
    browseURL(url)
}
```
I use this after I upload something to 1) sanity check myself that it is there and 2) do other actions like grab a share link or comment someone else

**Comment by ijlyttle** [comment]
I like this! Let's work on this idea!

**Comment by ijlyttle** [comment]
I think that we can use the address `app.box.com` and the browser will go to the right place, depending on where you are signed in. I'd have to check.
