### ISSUE TITLE
New home at r-box/boxr!

### ISSUE THREAD

**Issue by brendan-r** [r-box/boxr#99]
This isn't really an issue, but it seems the easiest way to let @ijlyttle  and @nathancday know that we've moved! Thanks to Ian in particular for suggesting this and starting the organization.

I also wanted to say thanks to you both for vastly improving this package and keeping it going, and apologize for being rather absent regarding package development (I'm afraid I have not used a box.com account for a couple of years).

There are of course plenty of links dotted around to brendan-r/boxr instead of r-box/boxr, but the ones I've tested seem to be redirecting. Sorry this took me a while!

**Comment by ijlyttle** [comment]
No worries - let me take this opportunity to thank @brendan-r, first for creating boxr, and second for entrusting it to us!

I don't wish to imply that Brendan is somehow going away, as we are still relying on him for knowing how things actually work around here :)
